### ISSUE TITLE
Rename repo to PyPeri or similar

### ISSUE THREAD

**Issue by gmingas** [alan-turing-institute/PeriPy#65]

**Comment by bb515** [comment]
PyPeri is taken, https://pyperi.readthedocs.io/en/latest/readme.html
but I don't think there will be much confusion if we name the repo to PeriPy, and if there is then the worst case is that the user has installed the wrong pacakage.

**Comment by gmingas** [comment]
Renamed repo to PeriPy just now. I have not changed anything in master, waiting for changes from the PR in dir names, readme, etc.

**Comment by bb515** [comment]
All names have been changed now in the PR
