### ISSUE TITLE
Move to PyPI

### ISSUE THREAD

**Issue by gmingas** [alan-turing-institute/PeriPy#74]
Good reference:
https://realpython.com/pypi-publish-python-package/

**Comment by bb515** [comment]
I've uploaded a test project here
https://test.pypi.org/project/peripy/0.1.0/
A couple of questions:
should peripy/test/, docs/, docs/_build,  be included in the package distribution?
I have generated the minimal html documentation which has roughly the same structure as NumPy docs, including a quickstart guide and an API reference.  I'll use this to upload the docs to PyPI https://pythonhosted.org/an_example_pypi_project/buildanduploadsphinx.html

**Comment by gmingas** [comment]
The tests should be included as the user should be able to run them locally.

`docs/` should be included too but not sure about `docs/_build`. What does the latter contain?

Also, the README file should be edited to say that installation is done using `pip install peripy` instead of using the repo. But it might be good to keep the link to the repo there for people that want to clone from github for any reason.

**Comment by gmingas** [comment]
Sorry, my mistake, it is probably not needed to include `docs` in the distribution. You can just upload them as you mentioned above. i don't think there would be any gain for the users to have them locally.

**Comment by bb515** [comment]
On a separate point, I don't believe https://realpython.com/pypi-publish-python-package/#different-ways-of-calling-a-package has any information on how our examples might be called once the package is installed without the use of a `__main__.py` file, or how tests will be run. I'll look into this tomorrow.

**Comment by bb515** [comment]
> On a separate point, I don't believe https://realpython.com/pypi-publish-python-package/#different-ways-of-calling-a-package has any information on how our examples might be called once the package is installed without the use of a `__main__.py` file, or how tests will be run. I'll look into this tomorrow.

Using [this](https://github.com/pypr/pysph/blob/master/pysph/tools/cli.py) and [this](https://github.com/pypr/pysph/blob/master/pysph/examples/run.py) code from pySPH as a template, I have made it so users can type "peripy run example1" and "peripy test" and "peripy coverage". For full changes see [this](https://github.com/alan-turing-institute/PeriPy/commit/978115a123d7aea0c57aa4396cc7380d09fd853b) and [this](https://github.com/alan-turing-institute/PeriPy/commit/3ffcdaaa312e6e45c0bb811b3d5fef149039c5c7) commit

**Comment by bb515** [comment]
Merge pull request #98 from alan-turing-institute/fix/PyPI
Fix/py pi
https://pypi.org/project/peripy/
